# Generated by Django 3.1.7 on 2021-04-15 06:39

from django.db import migrations, models
import django.utils.timezone
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_edited_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='posted_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to=posts.models.post_image_upload_url),
        ),
    ]
