# Generated by Django 3.1.7 on 2021-04-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210415_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('text', 'Text'), ('link', 'Link'), ('images', 'Images')], default='Text', max_length=6),
        ),
    ]
