# Generated by Django 3.1.7 on 2021-04-25 07:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0006_auto_20210415_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='downvoters',
            field=models.ManyToManyField(related_name='downvoted_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
