# Generated by Django 3.1.7 on 2021-04-25 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_auto_20210425_1313'),
        ('posts', '0007_auto_20210425_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='topics.topic'),
        ),
    ]
