# Generated by Django 3.1.7 on 2021-05-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hot_rank',
            field=models.FloatField(null=True),
        ),
    ]
