# Generated by Django 3.1.7 on 2021-04-25 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_auto_20210425_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='SidebarCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sidebar_cards', to='topics.topic')),
            ],
        ),
        migrations.DeleteModel(
            name='TopicCard',
        ),
    ]
