# Generated by Django 3.1.7 on 2021-05-31 03:48

from django.db import migrations, models
import topics.models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0007_auto_20210429_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='banner',
            field=models.ImageField(blank=True, upload_to=topics.models.get_topic_banner_path),
        ),
    ]
