# Generated by Django 3.1.7 on 2021-07-14 10:55

from django.db import migrations, models
import topics.models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0009_topic_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='icon',
            field=models.ImageField(blank=True, default='default_topic_icon.jpg', upload_to=topics.models.get_topic_icon_path),
        ),
    ]
