# Generated by Django 3.1.7 on 2021-04-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210415_1209'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='downvoted_posts',
            field=models.ManyToManyField(related_name='downvoters', to='posts.Post'),
        ),
        migrations.AddField(
            model_name='user',
            name='upvoted_posts',
            field=models.ManyToManyField(related_name='upvoters', to='posts.Post'),
        ),
    ]
