# Generated by Django 3.1.7 on 2021-04-15 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210415_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='downvoted_posts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='upvoted_posts',
        ),
    ]
