# Generated by Django 3.1.7 on 2021-05-30 11:03

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210509_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='default_profile_pic.png', upload_to=accounts.models.get_image_upload_path),
        ),
    ]
